### ISSUE TITLE
Introducing Code Conventions based upon JSLint

### ISSUE THREAD

**Issue by johanbove** [jqPlot/jqPlot#10]
I would like to refactor the JavaScript code to comply with [JsLint](http://www.jslint.com/) checks.
I've already started the refactoring in my fork and the jqplot-1 fork. In my opinion the project could benefit greatly from a more strict coding approach and making code pass JsLint strict rules is a good start.

**Comment by ppritcha** [comment]
I added a section for JSHint in the gruntfile, but did not yet make passing that a required step in the build, since there a lot of changes are required.  I used JSHint because its a newer tool and seems to be used by a lot of projects, but I'm open to either JSHint or JSLint.  Do you have any opinions about whether we should use JSLint instead of JSHint?

**Comment by johanbove** [comment]
Well, JSLint and JSHint are both code quality checking tools. They both
serve as "early warning systems" to tell the developer he or she did
something not following the rules. Now, the JSLint are more strict and
testing code using JSLint will almost always result in warnings. JSHint
allows for less agnostic code testing and is, as you said, more modern.
Personally I got used to using JSLint's strict rules, which luckily still
can be toned down a notch using global flags. The changes I made to the
code were done following "advice" and rules from JsLint. So therefore I did
do a lot of effort moving var declarations to the top of functions and
comma separating them. Over the years I got really used to this notation
since I believe it allows for quick glancing on what more complicated
module or bigger "function" will do and what will be used in the code. It
makes code more readable for me. Moving vars at the top will quickly point
out too high complexity or even missing vars. Although this highly depends
on which editor you're using.
I made the switch back to Notepad++ recently which is quiet powerful thanks
to a plethora of plugins, of which is a jslint / jshint one. I was good
with JSLint and I'm thinking I will be for some time to come.

On Tue, Oct 13, 2015 at 9:10 PM, Paul Pritchard <notifications@github.com>
wrote:

> I added a section for JSHint in the gruntfile, but did not yet make
> passing that a required step in the build, since there a lot of changes are
> required. I used JSHint because its a newer tool and seems to be used by a
> lot of projects, but I'm open to either JSHint or JSLint. Do you have any
> opinions about whether we should use JSLint instead of JSHint?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jqPlot/jqPlot/issues/10#issuecomment-147817417>.
>



-- 
Johan

--
http://johanbove.info

**Comment by ppritcha** [comment]
I switched the gruntfile.js to jslint, so we can do "grunt jslint" now.

**Comment by johanbove** [comment]
Cool. :+1:

On Mon, Nov 2, 2015 at 4:46 PM, Paul Pritchard <notifications@github.com>
wrote:

> I switched the gruntfile.js to jslint, so we can do "grunt jslint" now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jqPlot/jqPlot/issues/10#issuecomment-153058316>.
>



-- 
Johan

--
http://johanbove.info
