### ISSUE TITLE
FireFox v50.1.0 not showing graphs when using canvasAxisTickRenderer.

### ISSUE THREAD

**Issue by UWiX-nl** [jqPlot/jqPlot#120]
Starting from today bar graphs are not showing in Firefox when using canvasAxisTickRenderer.js. If I disable the loading of the .js it shows correctly.
In IE and Chrome is all works fine. It's not a miscoding issue because the same thing occurs when loading the example pages on www.jqplot.com (for rotating axis labels).

**Comment by PMeira** [comment]
I've found issues rendering paths in old versions of Chrome that ended up being something in the hardware acceleration pipeline (most likely the GPU driver).  
For the example page, mine is working fine (same output as Chrome) both with hardware acceleration and without it.

Could you try disabling hardware acceleration to make sure it's not related? To do so, visit about:preferences#advanced to uncheck "Use hardware acceleration when available", then restart Firefox.

**Comment by UWiX-nl** [comment]
Thanks for the "heads up" - tried disabling it - but does not seem to change the view, however......
Everything displays correctly now - with or without the hardware acceleration ?!?!?!?

Browser cache? Wierd Firefox issue? Yesterday I've tried everything, clearing cache, rebooting several times, etc. Now the next day all seems to work as it should.... Darn...

Anyhow - this issue can be closed, seems it has nothing to do with jqPlot, sorry about that. Thank you for your assistance, PMeira!
