### ISSUE TITLE
Domain for jqplot.com will expire 2018-03-27

### ISSUE THREAD

**Issue by johanbove** [jqPlot/jqPlot#134]
See: http://whois.domaintools.com/jqplot.com

I don't know who will be paying for a renewal of the domain to keep this project going, but I probably won't.

**Comment by ktw** [comment]
What about moving the documentation to GitHub Pages, and dropping the domain?

**Comment by johanbove** [comment]
Thanks for sharing the idea @ktw, but the challenge would be that the documentation is currently being generated using PHP, which is not available on GitHub pages; so that would have to be migrated and I'm afraid there is currently nobody to do that.

**Comment by johanbove** [comment]
This is up to @ppritcha actually. I don't have any ways of administrating the jQPlot.com website; nor do I have the time for it unfortunately.

**Comment by toolstack** [comment]
@ppritcha @johanbove Let me know if you need any help.  I can either help host it or rewrite the doc processor it to work with GitHub's wiki format (I don't think the examples would be possible on GitHub).

**Comment by chenster** [comment]
I can also help with PHP hosting. We can also host the a static copy of the documentation on Github.

**Comment by lambdaZ** [comment]
Hi all! How much the domain cost? I could pay for it.

**Comment by johanbove** [comment]
Thanks everybody for replying to this thread and you willingness to help out!

We have a real problem with the jqplot.com domain as the original creator and registrar for the domain jqplot.com has disappeared. I personally have no way to make changes to it.

I would suggest that we let the domain expire and someone who is willing to pick up the torch should then simply register.

Does anyone know how this can be organised in a "safe" way, so the domain name is not hi-jacked by people with lesser intentions?

**Comment by johanbove** [comment]
@lambdaZ  What do you of registering jqplot.org which would become jqplot's new home?

**Comment by lambdaZ** [comment]
Hi, johanbove! I am sorry for so big delay in response. I have a hosting, which is not highly loaded. So it is possible to transfer on it jqPlot site and domain. Does the problem with domain still exist or not? I checked the WhoIs database and the expiration date is 2019-03-27. Someone extended the domain validity. So, the problem is resolved, right?

**Comment by johanbove** [comment]
Thanks for following this up!
I'm really focused on other private projects now and any help to keep this
project alive, also for historical reasons, is welcome.

Johan

**Comment by johanbove** [comment]
It's unclear how at the moment, but it seems @cleonello or @ppritcha are still paying for the hosting, so I'm closing this issue. The current expiration is set to March 2019. Let's see what happens then.
