### ISSUE TITLE
Stable and minified version

### ISSUE THREAD

**Issue by nunomaduro** [jqPlot/jqPlot#15]
Hey,

Can you guys add an stable and minified version?

Example:

        
        <script src="jqPlot/dist/jquery.jqplot.min.js"></script>
        <script src="jqPlot/dist/extras/jqplot.dateAxisRenderer.min.js"></script>
        ... All the plugins that i want.

**Comment by ppritcha** [comment]
Go to the jqplot.com downloads page to get the latest stable version:  http://www.jqplot.com/download/.
