### ISSUE TITLE
Tests don't work on jqplot.com

### ISSUE THREAD

**Issue by nunomaduro** [jqPlot/jqPlot#16]
Browser: Chrome
OS: OSX

![screen shot 2015-10-08 at 10 36 10](https://cloud.githubusercontent.com/assets/5457236/10362783/864dc2f8-6da8-11e5-9491-0fb9a22a1459.png)

**Comment by ppritcha** [comment]
Looks like you were accessing an obsolete page on the site.  All of the tests and examples are on http://www.jqplot.com/examples.
