### ISSUE TITLE
Legend not using passed styles.

### ISSUE THREAD

**Issue by dwhipps** [jqPlot/jqPlot#160]
I think you're failing to use the style parameters passed to the Legend. They're correctly read-in, but never applied to the element. I think you need:
`this._elem.css(ss);`
Around line 7954 in `$.jqplot.TableLegendRenderer.prototype.draw` in order to apply the style object to the element.

**Comment by dg-spark** [comment]
@johanbove - Can this issue be closed now?

**Comment by johanbove** [comment]
Yes. Thanks!
