### ISSUE TITLE
is jQplot compatible with latest version of jquery ?

### ISSUE THREAD

**Issue by ashishoorja** [jqPlot/jqPlot#193]
Hi All,

Simple query : Just wanted to know if jQplot is compatible with jQuery version higher than 3.0 ?

**Comment by melloware** [comment]
Yes it seems to be

**Comment by ashishoorja** [comment]
what took you so long...

Regards,
Ashish Patel

**Comment by melloware** [comment]
I am not a committer or member of this project I just use JQPlot and letting you know I am using it with JQuery 3.5.1 fine.

**Comment by ashishoorja** [comment]
I m really sorry. It was a joke but you took preety seriously. Please do
help people the way you do. I m really sorry again.

**Comment by melloware** [comment]
No worries!

**Comment by Daijobou** [comment]
Your question was answered, so why do you not close this ticket? ;-)
