### ISSUE TITLE
Cursor Highlighter demo page not working

### ISSUE THREAD

**Issue by johanbove** [jqPlot/jqPlot#2]
The graphs on this page don't load: http://www.jqplot.com/examples/cursor-highlighter.php

``
Uncaught SyntaxError: Unexpected token <
jqplot.highlighter.js:32 Uncaught TypeError: Cannot read property 'eventListenerHooks' of undefined
jqplot.cursor.js:37 Uncaught TypeError: Cannot set property 'Cursor' of undefined
jqplot.dateAxisRenderer.js:108 Uncaught TypeError: Cannot set property 'DateAxisRenderer' of undefined
cursor-highlighter.php:63 Uncaught TypeError: Cannot read property 'DateAxisRenderer' of undefined
chrome-extension://gojbdfnpnhogfdgjbigejoaolejmgdhk/Tooltips/TooltipBootstrapper.js
``

**Comment by ppritcha** [comment]
That's fixed.
