### ISSUE TITLE
display total amount of items in the centre of a donut chart

### ISSUE THREAD

**Issue by jeschr** [jqPlot/jqPlot#20]
I was missing a functionality to display the total amount of items in the centre of a donut chart. The space in the centre of a donut is wasted anyway :-)
So I did a small enhancement that introduces a new rendererOption to the donutRenderer which does this (see attached patch file).

                    "rendererOptions": {
                             "totalLabel": "true"
                    }

Will result in something like this:
![total_amount_donut](https://cloud.githubusercontent.com/assets/7577275/10629437/1b79da26-77cf-11e5-800a-105c6761ebfd.png)

The patch file is quick-and-dirty only with functionality not concidering documentation. If you accept this enhancement I could alse extend this.

```patch
--- C:/Temp/tvc/jquery.jqplot.1.0.8r1250_ootb/dist/plugins/jqplot.donutRenderer.js	Di Mrz 26 20:28:18 2013
+++ C:/Temp/tvc/jquery.jqplot.1.0.8r1250/dist/plugins/jqplot.donutRenderer.js	Mi Okt 21 08:23:00 2015
@@ -132,6 +132,9 @@
         // prop: showDataLabels
         // true to show data labels on slices.
         this.showDataLabels = false;
+		// prop: totalLabel
+		// true to show total label in the centre
+		this.totalLabel = false;
         // prop: dataLabelFormatString
         // Format string for data labels.  If none, '%s' is used for "label" and for arrays, '%d' for value and '%d%%' for percentage.
         this.dataLabelFormatString = null;
@@ -263,6 +266,7 @@
             td[i][1] = stack[i] * fact;
             td[i][2] = data[i][1]/tot;
         }
+		this._totalAmount = tot;
         return td;
     };
     
@@ -450,7 +454,10 @@
                 labelelem.css({left: x, top: y});
             }
         }
-               
+		if (this.totalLabel) {
+			var totalLabel = $('<div class="jqplot-data-label" style="position:absolute">' + this._totalAmount + '</div>').insertAfter(plot.eventCanvas._elem);
+			totalLabel.css({left: this._center[0], top: this._center[1]});
+		}
     };
     
     $.jqplot.DonutAxisRenderer = function() {
```

**Comment by johanbove** [comment]
Great idea and it seem to be working great. Can you create a Pull Request for this change?

**Comment by jeschr** [comment]
Pull Request is created (#21)

**Comment by johanbove** [comment]
Merged.
