### ISSUE TITLE
Come up with a release schedule and tagging system

### ISSUE THREAD

**Issue by johanbove** [jqPlot/jqPlot#28]
Github allows for milestones and tagging of code; we should agree to come up with a release plan for jqplot.

The latest release is version jquery.jqplot.1.0.8r1250; We should have a tag in the GitHub repository to indicate which code base this release was made on.

The can be easily achieved using `npm version` which creates tag in the git repository.

When a new tag is created the tag should be pushed to the GitHub repository which will create a release automatically.

**Comment by maruilian11** [comment]
Hi @johanbove,
I'm from [cdnjs](https://github.com/cdnjs/cdnjs), we have hosted your lib on our [CDN service site](https://cdnjs.com). We actually support the auto-update function to update every version of libs, one is for npm package, the other is for git repo.

**Comment by johanbove** [comment]
Hi @maruilian11 First of all, my apologies for replying almost two years too late ...
Thanks for the suggestion for the tags so you can auto-update CDNJS, although we haven't done any releases since a long time and it doesn't look like we will as this project basically has gone stale. But the tips to use the tags is definitely interesting and if anyone is still interested in keeping this project alive than adding those will definitely help CDNJS and other CDNs.

**Comment by johanbove** [comment]
Added release tags.
