### ISSUE TITLE
Daylight Savings

### ISSUE THREAD

**Issue by ChrisRollason** [jqPlot/jqPlot#30]
Hi,

Not sure whether all the old issues will move from the old repository into the new one eventually.

I'm having trouble with the graph Date Axis Renderer handling daylight savings (in the UK).

It was raised in the old repository back in 2011.
https://bitbucket.org/cleonello/jqplot/issues/449/nov-6-showing-twice-in-x-axis

I'm trying to show five days worth of data.

When I view part of last week (which contained the daylight saving change over), I get an extra blank day tacked onto the end.

I've created a jsfiddle to show this happening.

http://jsfiddle.net/rollasoc/823dwav9/

if I view five days before this period (where no daylight saving change over occurs), I get the five days data shown correctly.

http://jsfiddle.net/rollasoc/rtqjfg8g/

So other than the data in the array the code should be the same.

Additionally I found this post in the Google forum (from 2010). 

https://groups.google.com/forum/#!topic/jqplot-users/E_G0zzoTC6k

and this additional issue in the old repository

https://bitbucket.org/cleonello/jqplot/issues/157/jqplotdateaxisrenderer-uses-local-time

**Comment by ChrisRollason** [comment]
In dateAxisRenderer

there is the line (around line 505)

min = Math.floor((min.getTime() - min.getUtcOffset())/ tempti) * tempti + min.getUtcOffset();

I took the adding off the utc offset off the end of the function, which appears to fix it for me, since before the daylight savings switch the utc offset is +1 hour, so when it calculates nttarget on the following line, I was getting an extra day.

min = Math.floor((min.getTime() - min.getUtcOffset()) / tempti)

Not sure this is the best fix, but it fixed my graph and when I tested back in March's daylight saving switch, it still appears to work.

**Comment by Ernestet** [comment]
I applied these changes to jsdate.js Release1.0.9 and it fixed my problem with the daylight savings time
https://github.com/josegrad/jqplot-rails/commit/d94c8238fb97629f0d08ad77daffc3c88d819469
