### ISSUE TITLE
pie charts not rendering

### ISSUE THREAD

**Issue by dseeley** [jqPlot/jqPlot#38]
Pie charts do not appear to be rendering in the latest commit (even in the examples).

**Comment by johanbove** [comment]
Can you provide more detail on what is happening please? Do you see any errors in the browser console for instance?

**Comment by dseeley** [comment]
I simply unzipped the latest to an empty directory on an apache server - this is what is seen (no errors in the console) on Chrome 46, IE11 and Firefox 42 (all other chart types render ok):

![pie_fail](https://cloud.githubusercontent.com/assets/5869991/11528805/e7ca1348-98e0-11e5-83d5-2a919c70d0a3.png)

**Comment by jeschr** [comment]
This is due to the change for high resolution displays (#23). e.g. "ctx.canvas.style.width" is empty here on my machine (FF42 + IE 11 tested) but ctx.canvas.width delivers the correct value.

**Comment by jeschr** [comment]
I tested a bit further and the main part of the adjustment from http://stackoverflow.com/questions/20221461/hidpi-retina-plot-drawing is missing in jqplot.core.js.
The "initCanvas" does not contain the recalculations for widht and heigth. Maybe it is not merged yet or got lost. Let me know if I should create a pull request for the adjustment or if the inital commited wants to do that.

**Comment by johanbove** [comment]
Please create a Pull Request to fix this. Sorry for late reply.

**Comment by jeschr** [comment]
Done with pull request #43

**Comment by johanbove** [comment]
Pie charts are rendering now. So will close this issue. But we have a new issue with the Donut charts. See issue #47

**Comment by jeschr** [comment]
Updated #47 with a fix.
