### ISSUE TITLE
Error in documentation/example

### ISSUE THREAD

**Issue by raiserle** [jqPlot/jqPlot#44]
Hi, on this page:

http://www.jqplot.com/examples/dashboardWidget.php

<link rel="stylesheet" type="text/css" hrf="../src/jquery.jqplot.css" />
<link rel="stylesheet" type="text/css" hrf="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/themes/smoothness/jquery-ui.css" />

must

<link rel="stylesheet" type="text/css" href="../src/jquery.jqplot.css" />
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/themes/smoothness/jquery-ui.css" />

**Comment by raiserle** [comment]
Oh.. HTML-Tags

link rel="stylesheet" type="text/css" hrf="../src/jquery.jqplot.css" /
link rel="stylesheet" type="text/css" hrf="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/themes/smoothness/jquery-ui.css" /

must

link rel="stylesheet" type="text/css" href="../src/jquery.jqplot.css" /
link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/themes/smoothness/jquery-ui.css" /



href, not hrf on location

**Comment by johanbove** [comment]
Thanks for reporting this typo!
