### ISSUE TITLE
Pie Chart not rendering correctly

### ISSUE THREAD

**Issue by johanbove** [jqPlot/jqPlot#47]
After this commit: 

https://github.com/jqPlot/jqPlot/commit/3ef5e450cf630768921143c7b8816eb9130ddabc

The Pie Charts are not rendering correctly any more.

*Current state:*
<img width="666" alt="20160114-piecharts-nok" src="https://cloud.githubusercontent.com/assets/922765/12328848/a0d4fd76-badd-11e5-890c-cfb4c563dab0.png">

*Previous:*
<img width="534" alt="20160114-piecharts-ok" src="https://cloud.githubusercontent.com/assets/922765/12328849/a0fa549a-badd-11e5-8752-7bf1f553514a.png">

**Comment by jeschr** [comment]
I could not reproduce this issue. Tested with several browsers (IE 10, FF 38 ESR, Chrome 47).
Tested with my branch and a current jqPlot-master download.

**Comment by jeschr** [comment]
Could you pls. test the attached fix. I was not able to reproduce this at first because on 72 dpi displays the issue did not occur. But now I was able to reproduce this on a 190 dpi display.

**Comment by johanbove** [comment]
This is fixed for me. Thanks!

**Comment by stefk** [comment]
I've just tried again at home (linux + chromium 47) but this time:

1. Like jeschr, I can't reproduce the donut scaling issue.
2. All pie charts are fine except the sixth example from "Pie charts and Options" and the first from "Pie charts and Options 2".  Neither of those are displayed (the legends are, though).

#49 doesn't fix that new issue.

**Comment by jeschr** [comment]
@stefk 

Regarding: 
	1.) It was dependent on your display resolution if you were able to notice the scaling issue. On "regular" PC screens you want notice the scaling issue. Only displays with more than 72dpi resolution have produced the scale issue (most modern tablets, cell phones, 4k displays and advanced notebook displays). However, this should be solved with #49.
	2.a) I strongly assume the sixth example from "Pie charts and Options" is not displayed on intention because every value is "0". This should be the wanted behavior for pie charts. As soon as you change at least one value to non-zero the pie gets displayed. Pls. try that.
	2.b) The first example from "Pie charts and Options 2" is rendered on my side. However it it contains a very long text for the first data entry "Verwerkende FruedenStunde Companaziert Eine industrie". The pie renderer does suppress the chart rendering if the diameter gets lower than 6 pixels (for good reasons). So maybe depending you used fonts and browser font config the legend might get to big on your side to render the pie. Pls. try to shorten the text for the first data entry and check if the chart gets rendered. If not pls. provide a screenshot.
	
	As far as I could rate not we have no issue here.

**Comment by stefk** [comment]
@jeschr, you're right on both points. Cheers.

**Comment by bulldozier** [comment]
This is not solved by #49.

There is still a bug related to canvasBackingScale. Whenever canvasBackingScale is set to a value other than 1, pie charts render incorrectly, essentially used the scaled width and height to draw the pie graph, but with everything else using the non-scaled width and height. When the canvasBackingScale is set to 1 (which is the case most of the time), you get this:

`
<canvas width="300" height="205" class="jqplot-base-canvas" style="position: absolute; left: 0px; top: 0px; width: 300px; height: 205px;"></canvas>
`

But when canvasBackingScale=2, which happens for iPhones and high-res mac monitors, you get this:

`
<canvas width="600" height="410" class="jqplot-base-canvas" style="position: absolute; left: 0px; top: 0px; width: 300px; height: 205px;"></canvas>
`

Whenever the latter occurs, exporting to PNG will make the chart twice as big as it should be, with the legend and labels having the correct size.
