### ISSUE TITLE
Can't get Ant to execute NaturalDocs without returning an error

### ISSUE THREAD

**Issue by johanbove** [jqPlot/jqPlot#5]
When I execute the NaturalDocs scripts directly from the command line it works.

I've branched out my changes to <https://github.com/johanbove/jqPlot-1/blob/NaturalDocs/build.xml>

The command which works is this: `> perl extras/NaturalDocs-1.52/NaturalDocs -r -i build -o HTML dist/docs -p NData/ -s default`

I tried using NaturalDocs 1.52

Ant error is this:
``
[exec] Can't locate NaturalDocs/Constants.pm in @INC (@INC contains: /Modules /usr/lib/perl5/5.8.8/msys /usr/lib/pe rl5/5.8.8 /usr/lib/perl5/site_perl/5.8.8/msys /usr/lib/perl5/site_perl/5.8.8 /usr/lib/perl5/site_perl .) at C:\Users\Joh an\Dropbox\Johan\workspace\active\jqPlot-1/extras/NaturalDocs-1.52/NaturalDocs.pl line 61.`
``

**Comment by ppritcha** [comment]
Version 1.4 is the one that has been working with jqPlot.  Is the same error occurring for you with that version?

**Comment by johanbove** [comment]
Sorry for late reply. The issue is probably due to differences on Windows. I haven't had the time to look into this in more detail yet. I disabled the doc rendering from the Ant build for now.

**Comment by ppritcha** [comment]
I think we can safely close this now that we've switched from Ant to Grunt.

**Comment by johanbove** [comment]
Well, actually. I still have been using Ant in this project and it has been
working alright. I'm not sure how far Paul is with moving to Grunt honestly.

On Tue, Oct 13, 2015 at 9:12 PM, Paul Pritchard <notifications@github.com>
wrote:

> Closed #5 <https://github.com/jqPlot/jqPlot/issues/5>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jqPlot/jqPlot/issues/5#event-434410944>.
>



-- 
Johan

--
http://johanbove.info

**Comment by johanbove** [comment]
I got the latest from master now and will try to get the grunt build working.
