### ISSUE TITLE
checkIntersection not compatible with $.jqplot.BarRenderer waterfall

### ISSUE THREAD

**Issue by dg-spark** [jqPlot/jqPlot#7]
The function `checkIntersection(gridpos, plot)` does not return an intersection for **negative** values in a waterfall plot. 

Specifically this plot: 
```javascript
renderer:$.jqplot.BarRenderer, rendererOptions:{waterfall:true} 
```

The fault impacts the use of the highlight plugin and mouse event handlers which rely on the checkIntersection function to return the intersection of the mouse cursor and bar. There are likely other impacts too.

The fault exists in inside 
```javascript
function checkIntersection(gridpos, plot)
```

*Line:3246 of jquery.jqplot.js* 
```javascript
if (x>points[0][0] && x<points[2][0] && y>points[2][1] && y<points[0][1]) { 
```

This is because for negative values in waterfall plots, array `points[0][1]` is the lower bound of the bar and `points[2][1]` is the upper bound of the bar. Therefore this bug can be resolved by modifying Line:3246 of jquery.jqplot.js to the following;
```javascript
if (x>points[0][0] && x<points[2][0] && ((y>points[2][1] && y<points[0][1])  || (y>points[0][1] && y<points[2][1])) ) {
```
And here is an example - Data Point 3 (-6) will not highlight
```html
<!DOCTYPE html>
	<head>
		<link class="include" rel="stylesheet" type="text/css" href="jquery.jqplot.css" />
		<script class="include" type="text/javascript" src="jquery.min.js"></script>
		<script class="include" type="text/javascript" src="jquery.jqplot.js"></script>
		<script class="include" type="text/javascript" src="jqplot.barRenderer.js"></script>
	</head>
	<body>
		<div id="chart1"></div>
		<script class="code" type="text/javascript">
		$(document).ready(function(){
			var plot1 = $.jqplot ('chart1', [[14, 5, -6]],{seriesDefaults:{
                renderer:$.jqplot.BarRenderer,rendererOptions:{waterfall:true}
            }});
		});
		</script>
	</body>
</html>	
```

**Comment by dg-spark** [comment]
Below is an example in Firefox debugger:
![code](https://cloud.githubusercontent.com/assets/14153818/9708638/ede472de-5572-11e5-8a07-8b0ee2c24242.png)

And here are the array values
![code2](https://cloud.githubusercontent.com/assets/14153818/9708639/f2ee8c10-5572-11e5-81bd-429eeebc2871.png)
![code3](https://cloud.githubusercontent.com/assets/14153818/9708640/fa55f8d0-5572-11e5-9885-299a83970a4a.png)

**Comment by johanbove** [comment]
Thanks for the work on this! Really appreciated.
