### ISSUE TITLE
Missing point labels 

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [jqPlot/jqPlot#71]
When example for point labels section is used, no point labels are displayed.
```
   $(document).ready(function(){
     var line1 = [14, 32, 41, 44, 40, 47, 53, 67];
     var plot1 = $.jqplot('chart', [line1], {
         title: 'Chart with Point Labels', 
         seriesDefaults: { 
           showMarker:false,
           pointLabels: { show:true } 
         }
     });
   });
```
Same for version 1.0.8 - tested in both Chrome/FF.

Am I missing something?

**Comment by smanisca** [comment]
make sure you are including all the necessary js & css  files..

<script type="text/javascript" src="../src/jquery.jqplot.js"></script>
<script type="text/javascript" src="../src/plugins/jqplot.pointLabels.js"></script>
<link rel="stylesheet" type="text/css" href="../src/jquery.jqplot.css" />

**Comment by jan-tosovsky-cz** [comment]
Sorry for the noise, I completely overlooked additional scripts have to be specified.

**Comment by johanbove** [comment]
Thanks @smanisca ! Closing this.
