### ISSUE TITLE
replot issue when hideZeros set to true

### ISSUE THREAD

**Issue by smanisca** [jqPlot/jqPlot#73]
When the chart options are set to hideZeros=true and the plot is redrawn `plotrevenue.replot({ resetAxes: false });` there is an undefined error in jqplot.pointLabels.js at **emptyForce()**. Adding a validation `if (p._elems[i])` resolves the problem for me.

`

```
$.jqplot.PointLabels.draw = function (sctx, options, plot) {
    var p = this.plugins.pointLabels;
    // set labels again in case they have changed.
    p.setLabels.call(this);
    // remove any previous labels
    for (var i=0; i<p._elems.length; i++) {
        // Memory Leaks patch
        // p._elems[i].remove();           
            p._elems[i].emptyForce();           
    }`
```
- Version: 1.0.8
- Revision: 1250

**Comment by spoonguard2k** [comment]
This was already via pull request #26
