### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by Trapulo** [jqPlot/jqPlot#9]
Is there some TS definitions available to use the library from TS?
It will be really useful...

**Comment by johanbove** [comment]
Hi. I don't think TypeScript definitions exist for jQplot.
Would you be willing to help us create this?

**Comment by Trapulo** [comment]
Sorry, too hard for me.

**Comment by ChrisRollason** [comment]
This would be a nice to have.

**Comment by AbhishekGarg** [comment]
I would be interested in helping to create the TypeScript definitions.
